### ISSUE TITLE
Special characters in stream title

### ISSUE THREAD

**Issue by Alexmothe93** [Alexmothe93/TwitchRecorder#1]
Specials chars in stream title can create error when creating recording file.
Must replace problematic chars.

**Comment by maxb2** [comment]
What special characters are problematic? It looks like you are already stripping the filename correctly with line 133:
 `filename = "".join(x for x in filename if x.isalnum() or x in [" ", "-", "_", "."])`

**Comment by Alexmothe93** [comment]
Some streamers use Unicode characters, like: ᴖᴥᴖ
